import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const settings = readFileSync("src/pages/Settings.vue", "utf8");

assert.match(settings, /data-settings-image2-page/);
assert.match(settings, /data-settings-image2-section="basic"/);
assert.match(settings, /data-settings-image2-card/);
assert.match(settings, /data-settings-image2-row/);
assert.match(settings, /data-settings-image2-select/);
assert.match(settings, /data-settings-image2-field/);
assert.match(settings, /data-settings-image2-page class="[^"]*\bw-full\b/);
assert.match(settings, /data-settings-image2-page class="[^"]*(?:^|\s)text-\[13px\](?:\s|")/);
assert.match(settings, /data-settings-image2-section="basic"[\s\S]*<p class="text-\[13px\] font-bold/);
assert.match(settings, /<span class="text-\[15px\] font-bold text-white">设备名称<\/span>/);
assert.match(settings, /data-settings-image2-field[\s\S]*class="[^"]*\bh-8\b[^"]*(?:^|\s)text-\[13px\](?:\s|")/);
assert.match(settings, /v-for="option in themeOptions"[\s\S]*class="[^"]*\bh-8\b[^"]*(?:^|\s)text-\[13px\](?:\s|")/);
assert.match(settings, /border-\[color:var\(--accent-line\)\] bg-\[color:var\(--accent-soft\)\] text-\[color:var\(--accent-text\)\]/);
assert.match(settings, /@blur="saveDeviceName"/);
assert.match(settings, /@change="savePort"/);
assert.match(settings, /@click="saveTheme\(option\.value\)"/);
assert.match(settings, /@click="saveCloseAction\(option\.value\)"/);
assert.doesNotMatch(settings, /min-h-\[72px\]/);
assert.doesNotMatch(settings, /sm:grid-cols-\[120px_minmax\(0,1fr\)\]/);
assert.doesNotMatch(settings, /xl:grid-cols-\[1fr_0\.85fr\]/);
assert.doesNotMatch(settings, /data-close-action-options[\s\S]*grid gap-2 rounded-2xl/);
assert.doesNotMatch(settings, /data-settings-image2-page class="[^"]*\bmx-auto\b/);
assert.doesNotMatch(settings, /data-settings-image2-page class="[^"]*\bmax-w-\[/);
assert.doesNotMatch(settings, /data-settings-image2-page class="[^"]*\btext-xs\b/);
assert.doesNotMatch(settings, /text-\[11px\]/);
assert.doesNotMatch(settings, /data-settings-image2-select class="[^"]*\bmax-w-\[330px\]/);
assert.doesNotMatch(settings, /border-white\/70 bg-white text-\[#202020\]/);
assert.doesNotMatch(settings, /shadow-\[0_0_10px_rgba\(255,255,255,0\.28\)\]/);
