import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const settings = readFileSync("src/pages/Settings.vue", "utf8");

assert.match(settings, /data-settings-image2-page/);
assert.match(settings, /data-settings-image2-section="basic"/);
assert.match(settings, /data-settings-image2-card/);
assert.match(settings, /data-settings-image2-row/);
assert.match(settings, /data-settings-image2-select/);
assert.match(settings, /data-settings-image2-field/);
assert.match(settings, /data-settings-image2-page class="[^"]*\bw-full\b/);
assert.match(settings, /data-settings-image2-page class="[^"]*(?:^|\s)text-\[13px\](?:\s|")/);
assert.match(settings, /data-settings-image2-section="basic"[\s\S]*<p class="text-\[13px\] font-bold/);
assert.match(settings, /<span class="text-\[15px\] font-bold text-white">设备名称<\/span>/);
assert.match(settings, /data-settings-image2-field[\s\S]*class="[^"]*\bh-8\b[^"]*(?:^|\s)text-\[13px\](?:\s|")/);
assert.match(settings, /data-device-name-copy[\s\S]*设备名称[\s\S]*用于局域网内识别这台设备[\s\S]*data-device-name-field/);
assert.match(settings, /data-device-name-field[\s\S]*class="[^"]*\bw-full\b[^"]*sm:w-\[180px\]/);
assert.doesNotMatch(settings, /data-device-name-control-row/);
assert.match(settings, /aria-label="主题外观"/);
assert.match(settings, /:value="draft\.theme"/);
assert.match(settings, /@change="saveTheme\(\(\$event\.target as HTMLSelectElement\)\.value as AppTheme\)"/);
assert.match(settings, /aria-label="关闭按钮行为"/);
assert.match(settings, /:value="draft\.closeAction"/);
assert.match(settings, /@change="saveCloseAction\(\(\$event\.target as HTMLSelectElement\)\.value as CloseAction\)"/);
assert.match(settings, /@blur="saveDeviceName"/);
assert.match(settings, /@change="savePort"/);
assert.doesNotMatch(settings, /@click="saveTheme\(option\.value\)"/);
assert.doesNotMatch(settings, /@click="saveCloseAction\(option\.value\)"/);
assert.doesNotMatch(settings, /min-h-\[72px\]/);
assert.doesNotMatch(settings, /sm:grid-cols-\[120px_minmax\(0,1fr\)\]/);
assert.doesNotMatch(settings, /xl:grid-cols-\[1fr_0\.85fr\]/);
assert.doesNotMatch(settings, /data-close-action-options[\s\S]*grid gap-2 rounded-2xl/);
assert.doesNotMatch(settings, /data-settings-image2-page class="[^"]*\bmx-auto\b/);
assert.doesNotMatch(settings, /data-settings-image2-page class="[^"]*\bmax-w-\[/);
assert.doesNotMatch(settings, /data-settings-image2-page class="[^"]*\btext-xs\b/);
assert.doesNotMatch(settings, /text-\[11px\]/);
assert.doesNotMatch(settings, /data-settings-image2-select class="[^"]*\bmax-w-\[330px\]/);
assert.doesNotMatch(settings, /border-white\/70 bg-white text-\[#202020\]/);
assert.doesNotMatch(settings, /shadow-\[0_0_10px_rgba\(255,255,255,0\.28\)\]/);
