import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const appShell = readFileSync("src/components/layout/AppShell.vue", "utf8");
const settings = readFileSync("src/pages/Settings.vue", "utf8");
const configStore = readFileSync("src/stores/config.ts", "utf8");
const style = readFileSync("src/style.css", "utf8");
const types = readFileSync("src/types/config.ts", "utf8");
const rootTheme = style.match(/:root \{[^}]*\}/)?.[0] ?? "";

assert.match(types, /type AppTheme\s*=\s*"copyBlue"\s*\|\s*"win11Dark"/);
assert.match(types, /theme:\s*AppTheme/);
assert.match(appShell, /\(\)\s*=>\s*configStore\.config\.theme/);
assert.match(appShell, /dataset\.appTheme\s*=\s*theme/);
assert.match(settings, /\(\)\s*=>\s*draft\.theme/);
assert.match(settings, /dataset\.appTheme\s*=\s*theme/);
assert.match(settings, /onBeforeUnmount/);
assert.match(settings, /configStore\.config\.theme/);
assert.match(settings, /Win11 深色/);
assert.match(settings, /themeOptions[\s\S]*value:\s*"win11Dark"[\s\S]*value:\s*"copyBlue"/);
assert.match(settings, /茶话绿/);
assert.match(settings, /茶话间深黑绿风格/);
assert.doesNotMatch(settings, /经典蓝|深蓝控制台/);
assert.match(configStore, /theme:\s*"win11Dark"/);
assert.match(style, /html\[data-app-theme="win11Dark"\]/);
assert.match(style, /--main-bg:\s*#202020;/);
assert.match(rootTheme, /--main-bg:\s*#0b100e;/);
assert.match(rootTheme, /--main-bg-soft:\s*#151d18;/);
assert.match(rootTheme, /--panel-bg:\s*rgba\(27, 36, 31, 0\.92\);/);
assert.match(rootTheme, /--theme-accent:\s*#35c85a;/);
assert.match(rootTheme, /--accent-text:\s*#7ff0a1;/);
assert.doesNotMatch(rootTheme, /#10203a|#2563eb|#7dd3fc/);
