import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const appShell = readFileSync("src/components/layout/AppShell.vue", "utf8");
const settings = readFileSync("src/pages/Settings.vue", "utf8");
const configStore = readFileSync("src/stores/config.ts", "utf8");
const style = readFileSync("src/style.css", "utf8");
const types = readFileSync("src/types/config.ts", "utf8");
const rootTheme = style.match(/:root \{[^}]*\}/)?.[0] ?? "";

assert.match(types, /type AppTheme\s*=\s*"copyBlue"\s*\|\s*"win11Dark"\s*\|\s*"macosLight"\s*\|\s*"macosDark"/);
assert.match(types, /theme:\s*AppTheme/);
assert.match(appShell, /\(\)\s*=>\s*configStore\.config\.theme/);
assert.match(appShell, /dataset\.appTheme\s*=\s*theme/);
assert.match(settings, /\(\)\s*=>\s*draft\.theme/);
assert.match(settings, /dataset\.appTheme\s*=\s*theme/);
assert.match(settings, /onBeforeUnmount/);
assert.match(settings, /configStore\.config\.theme/);
assert.match(settings, /Win11 \u6df1\u8272/);
assert.match(settings, /\u5348\u591c\u73bb\u7483/);
assert.match(settings, /\u77f3\u58a8\u767d\u96fe/);
assert.match(settings, /\u6e05\u96c5\u8336\u7eff/);
assert.match(settings, /themeOptions[\s\S]*value:\s*"win11Dark"[\s\S]*value:\s*"macosDark"[\s\S]*value:\s*"macosLight"[\s\S]*value:\s*"copyBlue"/);
assert.match(settings, /\u8336\u8bdd\u95f4\u6df1\u9ed1\u7eff\u98ce\u683c/);
assert.doesNotMatch(settings, /\u8336\u8bdd\u7eff/);
assert.doesNotMatch(settings, /\u77f3\u58a8\u96fe/);
assert.doesNotMatch(settings, /\u7ecf\u5178\u84dd|\u6df1\u84dd\u63a7\u5236\u53f0/);
assert.match(configStore, /theme:\s*"win11Dark"/);
assert.match(style, /html\[data-app-theme="win11Dark"\]/);
assert.match(style, /html\[data-app-theme="macosLight"\]/);
assert.match(style, /html\[data-app-theme="macosDark"\]/);
assert.match(style, /--main-bg:\s*#202020;/);
assert.match(style, /--clipboard-card-bg:\s*rgba\(255, 255, 255, 0\.78\);/);
assert.match(rootTheme, /--main-bg:\s*#0b100e;/);
assert.match(rootTheme, /--main-bg-soft:\s*#151d18;/);
assert.match(rootTheme, /--panel-bg:\s*rgba\(27, 36, 31, 0\.92\);/);
assert.match(rootTheme, /--theme-accent:\s*#35c85a;/);
assert.match(rootTheme, /--accent-text:\s*#7ff0a1;/);
assert.match(rootTheme, /--clipboard-card-bg:\s*rgba\(29, 40, 34, 0\.92\);/);
assert.doesNotMatch(rootTheme, /#10203a|#2563eb|#7dd3fc/);
