import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const titleBar = readFileSync("src/components/layout/TitleBar.vue", "utf8");

assert.match(titleBar, /data-titlebar-port/);
assert.match(titleBar, /data-titlebar-port-editor/);
assert.match(titleBar, /<ConnectionBadge[\s\S]*data-titlebar-port-editor/);
assert.match(titleBar, /loader-circle\.js/);
assert.match(titleBar, /chevron-up\.js/);
assert.match(titleBar, /chevron-down\.js/);
assert.match(titleBar, /w-\[92px\]/);
assert.doesNotMatch(titleBar, /ethernet-port\.js|pencil\.js/);
assert.match(titleBar, /webkit-inner-spin-button/);
assert.match(titleBar, /data-titlebar-port-stepper/);
assert.match(titleBar, /data-titlebar-port-stepper[\s\S]*bg-\[color:var\(--main-bg-deep\)\]/);
assert.match(titleBar, /data-titlebar-port-stepper[\s\S]*text-\[color:var\(--muted-text\)\]/);
assert.doesNotMatch(titleBar, /data-titlebar-port-stepper[\s\S]{0,180}bg-\[color:var\(--accent-soft\)\]/);
assert.match(titleBar, /@click="adjustPort\(1\)"/);
assert.match(titleBar, /@click="adjustPort\(-1\)"/);
assert.match(titleBar, /portInput\.value\?\.focus\(\)/);
assert.doesNotMatch(titleBar, /portInput\.value\?\.select\(\)/);
assert.match(titleBar, /:aria-label="`监听端口/);
assert.match(titleBar, /:aria-busy="portSaving"/);
assert.match(titleBar, /cursor-pointer/);
assert.match(titleBar, /v-model\.number="portDraft"/);
assert.match(titleBar, /data-titlebar-port-input/);
assert.match(titleBar, /input\[data-titlebar-port-input\]:focus-visible/);
assert.match(titleBar, /border: 0;[\s\S]*outline: 0;[\s\S]*box-shadow: none;/);
assert.match(titleBar, /min="1"/);
assert.match(titleBar, /max="65535"/);
assert.match(titleBar, /const wasRunning = statusStore\.status\.running/);
assert.match(titleBar, /await statusStore\.stop\(\)/);
assert.match(titleBar, /await configStore\.save\(\{/);
assert.match(titleBar, /if \(wasRunning\) \{[\s\S]*await statusStore\.start\(\)/);
assert.match(titleBar, /@keydown\.esc\.prevent="cancelPortEdit"/);
